### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by gregkatz** [Bosvark/varkOS#2]
Hi,

Nice work on this project. I'm trying to do something similar in rust also as a learning project. Because I am referencing your code, I was wondering what the license to use it is? I couldn't find anything in the repo.

Thanks!

**Comment by Bosvark** [comment]
Hi,
Thanks, great to know someone finds it useful. I never bothered with license when I originally did it. Anyway, I added one now.

Knock yourself out!

**Comment by gregkatz** [comment]
Thanks again!
